openapi: 3.0.1
info:
  title: Create a lending application
  description: |-
    The OpenAPI specification for creating a marketplace application using the [Paystack API](https://paystack.com/docs/api/).
    ### Prerequisites
    1. Sign up on [Paystack](https://paystack.com/signup) to get your secret API key
    2. Set your API key as an environment variable on [Postman](https://learning.postman.com/docs/sending-requests/variables/)

    The [Partial Debits](https://paystack.com/docs/payments/partial-debits) feature allows you to recover some revenue that would have otherwise been lost. It is currently available on request.
  version: 1.0.0
servers:
  - url: 'https://api.paystack.co'
    description: Base API endpoint
paths:
  /transaction/initialize:
    post:
      tags:
        - Transaction
      summary: Initialize Transaction
      operationId: transaction_initialize
      description: Create a new transaction
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transaction~1initialize/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - email
                - amount
              properties:
                email:
                  description: Customer's email address
                  type: string
                  example: person@email.com
                amount:
                  description: 'Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR'
                  type: integer
                  example: 10247
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                reference:
                  description: 'Unique transaction reference. Only -, ., = and alphanumeric characters allowed.'
                  type: string
                  example: 123.uniq=ref-
                callback_url:
                  description: 'Fully qualified url, e.g. https://example.com/ . Use this to override the callback url provided on the dashboard for this transaction'
                  type: string
                plan:
                  description: |-
                    If transaction is to create a subscription to a predefined plan, provide plan code here. 
                    This would invalidate the value provided in amount
                  type: string
                  example: PLN_123wede
                invoice_limit:
                  description: Number of times to charge customer during subscription to plan
                  type: integer
                metadata:
                  description: Stringified JSON object of custom data
                  type: object
                  example:
                    cart_id: 398
                    custom_fields:
                      - display_name: Invoice ID
                        variable_name: Invoice ID
                        value: 209
                      - display_name: Cart Items
                        variable_name: cart_items
                        value: '3 bananas, 12 mangoes'
                channels:
                  description: An array of payment channels to control what channels you want to make available to the user to make a payment with
                  type: array
                  items:
                    type: string
                    enum:
                      - card
                      - bank
                      - ussd
                      - qr
                      - eft
                      - mobile_money
                      - bank_transfer
                  example:
                    - card
                    - bank
                    - ussd
                    - qr
                    - eft
                    - mobile_money
                    - bank_transfer
                split_code:
                  description: The split code of the transaction split
                  type: string
                  example: SPL_123AbZ
                subaccount:
                  description: The code for the subaccount that owns the payment
                  type: string
                  example: ACCT_23abcdefgh
                transaction_charge:
                  description: |-
                    A flat fee to charge the subaccount for a transaction. 
                    This overrides the split percentage set when the subaccount was created
                  type: integer
                  example: 12300
                bearer:
                  description: The bearer of the transaction charge
                  type: string
                  enum:
                    - account
                    - subaccount
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Initiailize Transaction:
                  value:
                    status: true
                    message: Authorization URL created
                    data:
                      authorization_url: 'https://checkout.paystack.com/spnajmit2hgi2c1'
                      access_code: spandaoende
                      reference: ad123ada
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transaction/charge_authorization:
    post:
      tags:
        - Transaction
      summary: Charge Authorization
      operationId: transaction_chargeAuthorization
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transaction~1charge_authorization/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - email
                - amount
                - authorization_code
              properties:
                email:
                  description: Customer's email address used during the first transaction
                  type: string
                  example: person@email.com
                amount:
                  description: 'Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR'
                  type: integer
                  example: 10247
                authorization_code:
                  description: Valid authorization code to charge
                  type: string
                  example: AUTH_CODE
                reference:
                  description: 'Unique transaction reference. Only -, ., = and alphanumeric characters allowed.'
                  type: string
                  example: 123.uniq=ref-2
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                metadata:
                  description: Stringified JSON object of custom data
                  type: object
                  example:
                    cart_id: 398
                    custom_fields:
                      - display_name: Invoice ID
                        variable_name: Invoice ID
                        value: 209
                      - display_name: Cart Items
                        variable_name: cart_items
                        value: '3 bananas, 12 mangoes'
                split_code:
                  description: The split code of the transaction split
                  type: string
                  example: SPL_123AbZ
                subaccount:
                  description: The code for the subaccount that owns the payment
                  type: string
                  example: ACCT_23abcdefgh
                transaction_charge:
                  description: |-
                    A flat fee to charge the subaccount for a transaction. 
                    This overrides the split percentage set when the subaccount was created
                  type: integer
                  example: 12300
                bearer:
                  description: The bearer of the transaction charge
                  type: string
                  enum:
                    - account
                    - subaccount
                queue:
                  description: 'If you are making a scheduled charge call, it is a good idea to queue them so the processing system does not get overloaded causing transaction processing errors.'
                  type: boolean
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Charge Authorization:
                  value:
                    status: true
                    message: Charge attempted
                    data:
                      amount: 500000
                      currency: NGN
                      reference: 123.uniq=ref-2
                      metadata: 'cart_id:398, custom_fields:[{}]'
                      split_code: SPL_123AbZ
                      subaccount: ACCT_23abcdefgh
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transaction/partial_debit:
    post:
      tags:
        - Transaction
      summary: Partial Debit
      operationId: transaction_partialDebit
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transaction~1partial_debit/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - email
                - amount
                - authorization_code
                - currency
              properties:
                email:
                  description: Customer's email address
                  type: string
                  example: person@email.com
                amount:
                  description: 'Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR'
                  type: integer
                  example: 10247
                authorization_code:
                  description: Valid authorization code to charge
                  type: string
                  example: AUTH_CODE
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                reference:
                  description: 'Unique transaction reference. Only -, ., = and alphanumeric characters allowed.'
                  type: string
                  example: 123.uniq=ref-3
                at_least:
                  description: Minimum amount to charge
                  type: integer
                  example: 5500
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Partial Debit:
                  value:
                    status: true
                    message: Charge attempted
                    data:
                      amount: 10247
                      currency: NGN
                      transaction_date: '2022-09-22T07:36:03.000Z'
                      status: success
                      reference: dycmjmd23f1hygq
                      domain: test
                      metadata: ''
                      gateway_response: Approved
                      message: null
                      channel: card
                      ip_address: null
                      log: null
                      fees: 52
                      authorization:
                        authorization_code: AUTH_15qn6qmeip
                        bin: '408408'
                        last4: '4081'
                        exp_month: '12'
                        exp_year: '2030'
                        channel: card
                        card_type: 'visa '
                        bank: TEST BANK
                        country_code: NG
                        brand: visa
                        reusable: true
                        signature: SIG_yEXu7dLBeqG0kU7g95Ke
                        account_name: null
                      customer:
                        id: 54219771
                        first_name: null
                        last_name: null
                        email: some.other@body.com
                        customer_code: CUS_toq66lmva87v66g
                        phone: null
                        metadata: null
                        risk_action: default
                        international_format_phone: null
                      plan: 0
                      requested_amount: 10247
                      id: 2122110499
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /bank/resolve:
    get:
      tags:
        - Verification
      summary: Resolve Account Number
      operationId: verification_resolveAccountNumber
      parameters:
        - name: account_number
          in: query
          schema:
            type: integer
          example: 0022728151
        - name: bank_code
          in: query
          schema:
            type: integer
          example: 51
      responses:
        '200':
          description: Resolve Account Number
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Resolve Bank:
                  value:
                    status: true
                    message: Account number resolved
                    data:
                      account_number: 342391
                      account_name: Doe Jane Loren
                      bank_id: 9
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        '404':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transferrecipient:
    post:
      tags:
        - Transfer Recipient
      summary: Create Transfer Recipient
      operationId: transferrecipient_create
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transferrecipient/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - type
                - name
                - account_number
                - bank_code
              properties:
                type:
                  description: 'Recipient Type - nuban for NGN, mobile_money for MOMO in GHS, basa for ZAR and authorization for all.'
                  type: string
                  enum:
                    - nuban
                    - mobile_money
                    - basa
                    - authorization
                name:
                  description: Recipient's name
                  type: string
                  example: Ada Lovelace
                account_number:
                  description: Recipient's bank account number
                  type: string
                  example: '0000000000'
                bank_code:
                  description: Recipient's bank code. You can get the list of Bank Codes by calling the List Banks endpoint
                  type: string
                  example: '011'
                description:
                  description: A description for this recipient
                  type: string
                  example: Keeps our servers running
                currency:
                  description: Currency for the account receiving the transfer
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                authorization_code:
                  description: An authorization code from a previous transaction
                  type: string
                  example: AUTH_CODE
                metadata:
                  description: Stringified JSON object of custom data
                  type: string
                  example: |
                    {referrer_id: 123}
      responses:
        '201':
          description: Transfer Recipient Created
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Create Customer:
                  value:
                    status: true
                    message: Transfer recipient created successfully
                    data:
                      active: true
                      createdAt: 2022-09-16T08:31:43.321Z
                      currency: NGN
                      domain: live
                      id: 38770134
                      integration: 463433
                      metadata:
                        referrer_id: 123
                      name: Ada Lovelace
                      recipient_code: RCP_2fl8jmb2v3kbleb
                      type: nuban
                      updatedAt: 2022-09-16T08:31:43.321Z
                      is_deleted: false
                      isDeleted: false
                      details:
                        authorization_code: null
                        account_number: 0
                        account_name: Doe Jane Loren
                        bank_code: 9
                        bank_name: First Bank of Nigeria
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transfer:
    post:
      tags:
        - Transfer
      summary: Initiate Transfer
      operationId: transfer_initiate
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transfer/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - source
                - amount
                - recipient
              properties:
                source:
                  description: Where should we transfer from? Only balance is allowed for now
                  type: string
                  example: balance
                amount:
                  description: Amount to transfer in kobo if currency is NGN. pesewas if currency is GHS and cents for ZAR.
                  type: integer
                  example: 10234
                recipient:
                  description: The transfer recipient's code
                  type: string
                  example: RCP_CODE
                reason:
                  description: The reason or narration for the transfer.
                  type: string
                  example: Good job
                currency:
                  description: Specify the currency of the transfer. Defaults to NGN.
                  type: string
                reference:
                  description: |-
                    If specified, the field should be a unique identifier (in lowercase) for the object. 
                    Only -,_ and alphanumeric characters are allowed.
                  type: string
                  example: Transfer-123_unique
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Initiate Transfer:
                  value:
                    status: true
                    message: Transfer has been queued
                    data:
                      reference: on5hyz9poe
                      integration: 428626
                      domain: test
                      amount: 3794800
                      currency: NGN
                      source: balance
                      reason: Holiday Flexing
                      recipient: 6788170
                      status: success
                      transfer_code: TRF_fiyxvgkh71e717b
                      id: 23070321
                      createdAt: 2020-05-13T14:22:49.687Z
                      updatedAt: 2020-05-13T14:22:49.687Z
        '401':
          description: Unauthorized operation
          content:
            application/json:
              examples:
                No-Authorization-Header:
                  value:
                    status: false
                    message: No Authorization Header was found
                Bad-Authorization-Header:
                  value:
                    status: false
                    message: 'Format is Authorization Bearer [secret key]'
                Invalid-Key:
                  value:
                    status: false
                    message: Invalid key
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
        default:
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Customer:
      allOf:
        - type: object
          required:
            - email
          properties:
            email:
              description: Customer's email address
              type: string
        - type: object
          properties:
            first_name:
              description: Customer's first name
              type: string
              example: Some
            last_name:
              description: Customer's last name
              type: string
              example: Body
            phone:
              description: Customer's phone number
              type: string
              example: '+2348123456789'
            metadata:
              description: Stringified JSON object of custom data
              type: string
        - type: object
          required:
            - authorization_code
          properties:
            authorization_code:
              description: Customer's authorization code to be deactivated
              type: string
        - type: object
          required:
            - customer
          properties:
            customer:
              description: 'Customer''s code, or email address'
              type: string
            risk_action:
              description: |
                One of the possible risk actions [ default, allow, deny ]. allow to whitelist. 
                deny to blacklist. Customers start with a default risk action.
              type: string
              enum:
                - default
                - allow
                - deny
        - type: object
          required:
            - type
            - country
            - bvn
            - bank_code
            - account_number
          properties:
            type:
              description: Predefined types of identification.
              type: string
              enum:
                - bvn
                - bank_account
            country:
              description: Two-letter country code of identification issuer
              type: string
              example: NG
            bvn:
              description: Customer's Bank Verification Number
              type: integer
              example: 0123456789
            bank_code:
              description: 'You can get the list of bank codes by calling the List Banks endpoint (https://api.paystack.co/bank).'
              type: string
              example: '007'
            account_number:
              description: Customer's bank account number.
              type: string
              example: '0111111111'
            first_name:
              description: Customer's first name
              type: string
              example: Uchenna
            last_name:
              description: Customer's last name
              type: string
              example: Okoro
    Error:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
    Response:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        data:
          type: object
  responses:
    Ok:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
              message:
                type: string
              data:
                type: object
    Created:
      description: Resource created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Entity not found
    Unauthorized:
      description: Unauthorized operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Invalid key
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - bearerAuth: []
