openapi: 3.0.1
info:
  title: Create an online marketplace
  description: The OpenAPI specification for creating an online marketplace using the Paystack API
  version: 1.0.0
servers:
  - url: 'https://api.paystack.co'
    description: Base API endpoint
paths:
  /subaccount:
    post:
      tags:
        - Subaccount
      summary: Create Subaccount
      operationId: subaccount_create
      description: Create a new subaccount
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1subaccount/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - business_name
                - settlement_bank
                - account_number
                - percentage_charge
              properties:
                business_name:
                  description: Name of business for subaccount
                  type: string
                  example: Some Subaccount
                settlement_bank:
                  description: Bank code for the bank. You can get the list of Bank Codes by calling the List Banks endpoint.
                  type: string
                  example: 11
                account_number:
                  description: Bank account number
                  type: string
                  example: 0
                percentage_charge:
                  description: Transaction percentage that the subaccount gets
                  type: number
                  format: float
                  example: 0.3
                description:
                  description: A description for this subaccount
                  type: string
                  example: A service provider
                primary_contact_email:
                  description: A contact email for the subaccount
                  type: string
                  example: sub@example.com
                primary_contact_name:
                  description: The name of the contact person for this subaccount
                  type: string
                  example: person@example.com
                primary_contact_phone:
                  description: A phone number to call for this subaccount
                  type: string
                metadata:
                  description: Stringified JSON object of custom data
                  type: string
                  example: |
                    {"category": "General supplies" }
      responses:
        '200':
          $ref: '#/paths/~1split/post/responses/200'
        '401':
          $ref: '#/paths/~1split/post/responses/401'
        default:
          description: Server error
  /split:
    post:
      tags:
        - Split
      summary: Create Split
      operationId: split_create
      description: Create a new transaction split
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1split/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - name
                - type
                - subaccounts
                - currency
              properties:
                name:
                  description: Name of the transaction split
                  type: string
                type:
                  description: The type of transaction split you want to create.
                  type: string
                  enum:
                    - percentage
                    - flat
                subaccounts:
                  description: A list of object containing subaccount code and number of shares
                  type: array
                  items:
                    type: object
                    properties:
                      subaccount:
                        description: Subaccount code of the customer or partner
                        type: string
                      share:
                        description: The percentage or flat quota of the customer or partner
                        type: string
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                bearer_type:
                  description: This allows you specify how the transaction charge should be processed
                  type: string
                  enum:
                    - subaccount
                    - account
                    - all-proportional
                    - all
                bearer_subaccount:
                  description: This is the subaccount code of the customer or partner that would bear the transaction charge if you specified subaccount as the bearer type
                  type: string
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Initiailize Transaction:
                  value:
                    status: true
                    message: Authorization URL created
                    data:
                      authorization_url: 'https://checkout.paystack.com/spnajmit2hgi2c1'
                      access_code: spandaoende
                      reference: ad123ada
                Charge Authorization:
                  value:
                    status: true
                    message: Charge attempted
                    data:
                      amount: 500000
                      currency: NGN
                      reference: 123.uniq=ref-2
                      metadata:
                        'cart_id:398 custom_fields':
                          - {}
                      split_code: SPL_123AbZ
                      subaccount: ACCT_23abcdefgh
                Resolve Account Number:
                  value:
                    status: true
                    message: Account number resolved
                    data:
                      account_number: 1234567
                      account_name: Doe Jane Loren
                      bank_id: 9
                Initiate Transfer:
                  value:
                    status: true
                    message: Transfer has been queued
                    data:
                      reference: on5hyz9poe
                      integration: 428626
                      domain: test
                      amount: 3794800
                      currency: NGN
                      source: balance
                      reason: Holiday Flexing
                      recipient: 6788170
                      status: success
                      transfer_code: TRF_fiyxvgkh71e717b
                      id: 23070321
                      createdAt: 2020-05-13T14:22:49.687Z
                      updatedAt: 2020-05-13T14:22:49.687Z
                Initiate Bulk Transfer:
                  value:
                    status: true
                    message: 2 transfers queued.
                    data:
                      - recipient: RCP_1a25w1h3n0xctjg
                        amount: 50000
                        transfer_code: TRF_mi8oa4liagyvq2md
                        currency: NGN
                        status: success
                      - recipient: RCP_sa1k1btncp993q1
                        amount: 50000
                        transfer_code: TRF_1c5upr4hp85l93n7
                        currency: NGN
                        status: success
                Create Subaccount:
                  value:
                    status: true
                    message: Subaccount created
                    data:
                      business_name: Cheese Sticks
                      account_number: 123456789
                      percentage_charge: 0.2
                      settlement_bank: Guaranty Trust Bank
                      integration: 428626
                      domain: test
                      subaccount_code: ACCT_xxxxxxxxxxxxx
                      is_verified: false
                      settlement_schedule: AUTO
                      active: true
                      migrate: false
                      id: 37614
                      createdAt: 2020-05-19T11:54:20.655Z
                      updatedAt: 2020-05-19T11:54:20.655Z
                Create Split:
                  value:
                    status: true
                    message: Split created
                    data:
                      id: 142
                      name: Test Doc
                      type: percentage
                      currency: NGN
                      integration: 428626
                      domain: test
                      split_code: SPL_e7jnRLtzla
                      active: true
                      bearer_type: subaccount
                      bearer_subaccount: 40809
                      createdAt: 2020-06-30T11:42:29.150Z
                      updatedAt: 2020-06-30T11:42:29.150Z
                      subaccounts:
                        - subaccount:
                            id: 40809
                            subaccount_code: ACCT_z3x6z3nbo14xsil
                            business_name: Business Name
                            description: Business Description
                            primary_contact_name: null
                            primary_contact_email: null
                            primary_contact_phone: null
                            metadata: null
                            percentage_charge: 20
                            settlement_bank: Business Bank
                            account_number: 1234567890
                          share: 20
                        - subaccount:
                            id: 40809
                            subaccount_code: ACCT_pwwualwty4nhq9d
                            business_name: Business Name
                            description: Business Description
                            primary_contact_name: null
                            primary_contact_email: null
                            primary_contact_phone: null
                            metadata: null
                            percentage_charge: 20
                            settlement_bank: Business Bank
                            account_number: 123456789
                          share: 30
                      total_subaccounts: 2
                Create Refund:
                  value:
                    status: true
                    message: Refund has been queued for processing
                    data:
                      transaction:
                        id: 1004723697
                        domain: live
                        reference: T685312322670591
                        amount: 10000
                        paid_at: '2021-08-20T18:34:11.000Z'
                        channel: apple_pay
                        currency: NGN
                        authorization:
                          exp_month: null
                          exp_year: null
                          account_name: null
                        customer:
                          international_format_phone: null
                        plan: {}
                        subaccount:
                          currency: null
                        split: {}
                        order_id: null
                        paidAt: '2021-08-20T18:34:11.000Z'
                        pos_transaction_data: null
                        source: null
                        fees_breakdown: null
                      integration: 412829
                      deducted_amount: 0
                      channel: null
                      merchant_note: Refund for transaction T685312322670591 by test@me.com
                      customer_note: Refund for transaction T685312322670591
                      status: pending
                      refunded_by: test@me.com
                      expected_at: '2021-12-16T09:21:17.016Z'
                      currency: NGN
                      domain: live
                      amount: 10000
                      fully_deducted: false
                      id: 3018284
                      createdAt: '2021-12-07T09:21:17.122Z'
                      updatedAt: '2021-12-07T09:21:17.122Z'
        '401':
          description: Unauthorized operation
          content:
            application/json:
              examples:
                No_Authorization_Header:
                  value:
                    status: false
                    message: No Authorization Header was found
                Bad-Authorization-Header:
                  value:
                    status: false
                    message: 'Format is Authorization Bearer [secret key]'
                Invalid_Key:
                  value:
                    status: false
                    message: Invalid key
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
        default:
          description: Server error
  /transaction/initialize:
    post:
      tags:
        - Transaction
      summary: Initialize Transaction
      operationId: transaction_initialize
      description: Create a new transaction
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transaction~1initialize/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - email
                - amount
              properties:
                email:
                  description: Customer's email address
                  type: string
                  example: person@email.com
                amount:
                  description: 'Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR'
                  type: integer
                  example: 10247
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                reference:
                  description: 'Unique transaction reference. Only -, ., = and alphanumeric characters allowed.'
                  type: string
                  example: 123.uniq=ref-
                callback_url:
                  description: 'Fully qualified url, e.g. https://example.com/ . Use this to override the callback url provided on the dashboard for this transaction'
                  type: string
                plan:
                  description: |-
                    If transaction is to create a subscription to a predefined plan, provide plan code here. 
                    This would invalidate the value provided in amount
                  type: string
                  example: PLN_123wede
                invoice_limit:
                  description: Number of times to charge customer during subscription to plan
                  type: integer
                metadata:
                  description: Stringified JSON object of custom data
                  type: string
                  example: |
                    {"cart_id":398, "custom_fields": [{
                        "display_name":"Invoice ID",
                        "variable_name":"Invoice ID",
                        "value":209
                      },
                                  {
                                    "display_name":"Cart Items",
                                    "variable_name":"cart_items",
                                    "value":"3 bananas, 12 mangoes"
                                  }
                                ]
                              }
                    }
                channels:
                  description: An array of payment channels to control what channels you want to make available to the user to make a payment with
                  type: array
                  items:
                    type: string
                    enum:
                      - card
                      - bank
                      - ussd
                      - qr
                      - eft
                      - mobile_money
                      - bank_transfer
                  example:
                    - card
                    - bank
                    - ussd
                    - qr
                    - eft
                    - mobile_money
                    - bank_transfer
                split_code:
                  description: The split code of the transaction split
                  type: string
                  example: SPL_123AbZ
                subaccount:
                  description: The code for the subaccount that owns the payment
                  type: string
                  example: ACCT_23abcdefgh
                transaction_charge:
                  description: |-
                    A flat fee to charge the subaccount for a transaction. 
                    This overrides the split percentage set when the subaccount was created
                  type: string
                  example: 12300
                bearer:
                  description: The bearer of the transaction charge
                  type: string
                  enum:
                    - account
                    - subaccount
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Initiailize Transaction:
                  $ref: '#/paths/~1split/post/responses/200/content/application~1json/examples/Initiailize%20Transaction'
        '401':
          $ref: '#/paths/~1split/post/responses/401'
        default:
          description: Server error
  /refund:
    post:
      tags:
        - Refund
      summary: Create Refund
      operationId: refund_create
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1refund/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - transaction
              properties:
                transaction:
                  description: Transaction reference or id
                  type: string
                amount:
                  description: |-
                    Amount ( in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR ) to be refunded to the customer. 
                    Amount cannot be more than the original transaction amount
                  type: integer
                currency:
                  description: Three-letter ISO currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                customer_note:
                  description: Customer reason
                  type: string
                merchant_note:
                  description: Merchant reason
                  type: string
      responses:
        '200':
          $ref: '#/paths/~1split/post/responses/200'
        '401':
          $ref: '#/paths/~1split/post/responses/401'
        default:
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Customer:
      allOf:
        - type: object
          required:
            - email
          properties:
            email:
              description: Customer's email address
              type: string
        - type: object
          properties:
            first_name:
              description: Customer's first name
              type: string
            last_name:
              description: Customer's last name
              type: string
            phone:
              description: Customer's phone number
              type: string
            metadata:
              description: Stringified JSON object of custom data
              type: string
        - type: object
          required:
            - authorization_code
          properties:
            authorization_code:
              description: Customer's authorization code to be deactivated
              type: string
        - type: object
          required:
            - customer
          properties:
            customer:
              description: 'Customer''s code, or email address'
              type: string
            risk_action:
              description: |
                One of the possible risk actions [ default, allow, deny ]. allow to whitelist. 
                deny to blacklist. Customers start with a default risk action.
              type: string
              enum:
                - default
                - allow
                - deny
        - type: object
          required:
            - type
            - country
            - bvn
            - bank_code
            - account_number
          properties:
            type:
              description: Predefined types of identification.
              type: string
              enum:
                - bvn
                - bank_account
            country:
              description: Two-letter country code of identification issuer
              type: string
            bvn:
              description: Customer's Bank Verification Number
              type: string
            bank_code:
              description: 'You can get the list of bank codes by calling the List Banks endpoint (https://api.paystack.co/bank).'
              type: string
            account_number:
              description: Customer's bank account number.
              type: string
            value:
              description: Customer's identification number. Required if type is bvn
              type: string
    Error:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
    Response:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        data:
          type: object
  responses:
    Ok:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
              message:
                type: string
              data:
                type: object
    Created:
      description: Resource created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Entity not found
    Unauthorized:
      description: Unauthorized operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Invalid key
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - bearerAuth: []
