openapi: 3.0.1
info:
  title: Create a savings application
  description: |-
    The OpenAPI specification for creating a savings application using the [Paystack API](https://paystack.com/docs/api/).
    ### Prerequisites
    1. Sign up on [Paystack](https://paystack.com/signup) to get your secret API key
    2. Set your API key as an environment variable on [Postman](https://learning.postman.com/docs/sending-requests/variables/)

    Once setup, start with the [Initialize Transaction endpoint](https://paystack.com/docs/api/#transaction-initialize), where you'll open the `authorization_url` to load the Paystack Checkout and complete the transaction.
  version: 1.0.0
servers:
  - url: 'https://api.paystack.co'
    description: Base API endpoint
paths:
  /transaction/initialize:
    post:
      tags:
        - Transaction
      summary: Initialize Transaction
      operationId: transaction_initialize
      description: Create a new transaction
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transaction~1initialize/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - email
                - amount
              properties:
                email:
                  description: Customer's email address
                  type: string
                  example: person@email.com
                amount:
                  description: 'Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR'
                  type: integer
                  example: 10247
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                reference:
                  description: 'Unique transaction reference. Only -, ., = and alphanumeric characters allowed.'
                  type: string
                  example: 123.uniq=ref-
                callback_url:
                  description: Fully qualified url. Use this to override the callback url provided on the dashboard for this transaction
                  type: string
                  example: 'https://example.com/'
                plan:
                  description: |-
                    If transaction is to create a subscription to a predefined plan, provide plan code here. 
                    This would invalidate the value provided in amount
                  type: string
                  example: PLN_123wede
                invoice_limit:
                  description: Number of times to charge customer during subscription to plan
                  type: integer
                  example: 10
                metadata:
                  description: Stringified JSON object of custom data
                  type: object
                  example:
                    metadata:
                      cart_id: 398
                      custom_fields:
                        - display_name: Invoice ID
                          variable_name: Invoice ID
                          value: 209
                        - display_name: Cart Items
                          variable_name: cart_items
                          value: '3 bananas, 12 mangoes'
                channels:
                  description: An array of payment channels to control what channels you want to make available to the user to make a payment with
                  type: array
                  items:
                    type: string
                    example: '[''card'', ''bank'',''ussd'', ''qr'', ''eft'', ''mobile_money'', ''bank_transfer'']'
                split_code:
                  description: The split code of the transaction split
                  type: string
                  example: SPL_123AbZ
                subaccount:
                  description: The code for the subaccount that owns the payment
                  type: string
                  example: ACCT_23abcdefgh
                transaction_charge:
                  description: |-
                    A flat fee to charge the subaccount for a transaction. 
                    This overrides the split percentage set when the subaccount was created
                  type: integer
                  example: 12300
                bearer:
                  description: The bearer of the transaction charge
                  type: string
                  enum:
                    - account
                    - subaccount
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Initiailize Transaction:
                  value:
                    status: true
                    message: Authorization URL created
                    data:
                      authorization_url: 'https://checkout.paystack.com/spnajmit2hgi2c1'
                      access_code: spandaoende
                      reference: ad123ada
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transaction/charge_authorization:
    post:
      tags:
        - Transaction
      summary: Charge Authorization
      operationId: transaction_chargeAuthorization
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transaction~1charge_authorization/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - email
                - amount
                - authorization_code
              properties:
                email:
                  description: Customer's email address used during the first transaction
                  type: string
                  example: person@email.com
                amount:
                  description: 'Amount should be in kobo if currency is NGN, pesewas, if currency is GHS, and cents, if currency is ZAR'
                  type: integer
                  example: 10247
                authorization_code:
                  description: Valid authorization code to charge
                  type: string
                  example: AUTH_CODE
                reference:
                  description: 'Unique transaction reference. Only -, ., = and alphanumeric characters allowed.'
                  type: string
                  example: 123.uniq=ref-2
                currency:
                  description: The transaction currency
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - USD
                metadata:
                  description: Stringified JSON object of custom data
                  type: object
                  example:
                    cart_id: 398
                    custom_fields:
                      - display_name: Invoice ID
                        variable_name: Invoice ID
                        value: 209
                      - display_name: Cart Items
                        variable_name: cart_items
                        value: '3 bananas, 12 mangoes'
                split_code:
                  description: The split code of the transaction split
                  type: string
                  example: SPL_123AbZ
                subaccount:
                  description: The code for the subaccount that owns the payment
                  type: string
                  example: ACCT_23abcdefgh
                transaction_charge:
                  description: |-
                    A flat fee to charge the subaccount for a transaction. 
                    This overrides the split percentage set when the subaccount was created
                  type: integer
                  example: 12300
                bearer:
                  description: The bearer of the transaction charge
                  type: string
                  enum:
                    - account
                    - subaccount
                queue:
                  description: 'If you are making a scheduled charge call, it is a good idea to queue them so the processing system does not get overloaded causing transaction processing errors.'
                  type: boolean
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Charge Authorization:
                  value:
                    status: true
                    message: Charge attempted
                    data:
                      amount: 500000
                      currency: NGN
                      reference: 123.uniq=ref-2
                      metadata:
                        cart_id: 398
                        custom_fields:
                          - display_name: Invoice ID
                            variable_name: Invoice ID
                            value: 209
                      split_code: SPL_123AbZ
                      subaccount: ACCT_23abcdefgh
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /bank/resolve:
    get:
      tags:
        - Verification
      summary: Resolve Account Number
      operationId: verification_resolveAccountNumber
      parameters:
        - name: account_number
          in: query
          schema:
            type: integer
          example: 0022728151
        - name: bank_code
          in: query
          schema:
            type: integer
          example: 51
      responses:
        '200':
          description: Resolve Account Number
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Resolve Bank:
                  value:
                    status: true
                    message: Account number resolved
                    data:
                      account_number: 342391
                      account_name: Doe Jane Loren
                      bank_id: 9
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        '404':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transferrecipient:
    post:
      tags:
        - Transfer Recipient
      summary: Create Transfer Recipient
      operationId: transferrecipient_create
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transferrecipient/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - type
                - name
                - account_number
                - bank_code
              properties:
                type:
                  description: 'Recipient Type - nuban for NGN, mobile_money for MOMO in GHS, basa for ZAR and authorization for all.'
                  type: string
                  enum:
                    - nuban
                    - mobile_money
                    - basa
                    - authorization
                name:
                  description: Recipient's name
                  type: string
                  example: Ada Lovelace
                account_number:
                  description: Recipient's bank account number
                  type: string
                  example: '0000000000'
                bank_code:
                  description: Recipient's bank code. You can get the list of Bank Codes by calling the List Banks endpoint
                  type: string
                  example: '011'
                description:
                  description: A description for this recipient
                  type: string
                  example: Keeps our servers running
                currency:
                  description: Currency for the account receiving the transfer
                  type: string
                  enum:
                    - NGN
                    - GHS
                    - ZAR
                    - KES
                authorization_code:
                  description: An authorization code from a previous transaction
                  type: string
                  example: AUTH_CODE
                metadata:
                  description: Stringified JSON object of custom data
                  type: string
                  example: |
                    {referrer_id: 123}
      responses:
        '201':
          description: Transfer Recipient Created
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Create Customer:
                  value:
                    status: true
                    message: Transfer recipient created successfully
                    data:
                      active: true
                      createdAt: 2022-09-16T08:31:43.321Z
                      currency: NGN
                      domain: live
                      id: 38770134
                      integration: 463433
                      metadata:
                        referrer_id: 123
                      name: Ada Lovelace
                      recipient_code: RCP_2fl8jmb2v3kbleb
                      type: nuban
                      updatedAt: 2022-09-16T08:31:43.321Z
                      is_deleted: false
                      isDeleted: false
                      details:
                        authorization_code: null
                        account_number: 0
                        account_name: Doe Jane Loren
                        bank_code: 9
                        bank_name: First Bank of Nigeria
        '401':
          $ref: '#/paths/~1transfer/post/responses/401'
        default:
          description: Server error
  /transfer:
    post:
      tags:
        - Transfer
      summary: Initiate Transfer
      operationId: transfer_initiate
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/paths/~1transfer/post/requestBody/content/application~1json/schema'
          application/json:
            schema:
              type: object
              required:
                - source
                - amount
                - recipient
              properties:
                source:
                  description: Where should we transfer from? Only balance is allowed for now
                  type: string
                  example: balance
                amount:
                  description: Amount to transfer in kobo if currency is NGN. pesewas if currency is GHS and cents for ZAR.
                  type: integer
                  example: 10234
                recipient:
                  description: The transfer recipient's code
                  type: string
                  example: RCP_CODE
                reason:
                  description: The reason or narration for the transfer.
                  type: string
                  example: Good job
                currency:
                  description: Specify the currency of the transfer. Defaults to NGN.
                  type: string
                reference:
                  description: |-
                    If specified, the field should be a unique identifier (in lowercase) for the object. 
                    Only -,_ and alphanumeric characters are allowed.
                  type: string
                  example: Transfer-123_unique
      responses:
        '200':
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Ok/content/application~1json/schema'
              examples:
                Initiate Transfer:
                  value:
                    status: true
                    message: Transfer has been queued
                    data:
                      reference: on5hyz9poe
                      integration: 428626
                      domain: test
                      amount: 3794800
                      currency: NGN
                      source: balance
                      reason: Holiday Flexing
                      recipient: 6788170
                      status: success
                      transfer_code: TRF_fiyxvgkh71e717b
                      id: 23070321
                      failures: null
                      source_details: null
                      request: 654770431
                      transferred_at: 2020-05-13T14:22:49.687Z
                      transfersessionid: []
                      createdAt: 2020-05-13T14:22:49.687Z
                      updatedAt: 2020-05-13T14:22:49.687Z
                Bulk Transfers:
                  value:
                    status: true
                    message: 2 transfers queued.
                    data:
                      - reference: abc-12345679abc
                        recipient: RCP_1a25w1h3n0xctjg
                        amount: 50000
                        transfer_code: TRF_mi8oa4liagyvq2md
                        currency: NGN
                        status: pending
                      - reference: abc-123457
                        recipient: RCP_sa1k1btncp993q1
                        amount: 50000
                        transfer_code: TRF_1c5upr4hp85l93n7
                        currency: NGN
                        status: pending
                Finalize Transfer:
                  value:
                    status: true
                    message: Transfer has been queued
                    data:
                      domain: test
                      amount: 1000000
                      currency: NGN
                      reference: n7ll9pzl6b
                      source: balance
                      source_details: null
                      reason: E go better for you
                      status: pending
                      transfer_code: TRF_zuirlnr9qblgfko
                      titan_code: null
                      id: 529410
                      integration: 123460
                      recipient: 225204
                      createdAt: '2018-08-02T10:02:55.000Z'
                      updatedAt: '2018-08-02T10:12:05.000Z'
                List Transfers:
                  value:
                    status: true
                    message: Transfers retrieved
                    data:
                      - amount: 1187500
                        createdAt: '2024-03-07T16:13:42.000Z'
                        currency: NGN
                        domain: live
                        failures: null
                        id: 480480480480
                        integration: 463433
                        reason: transfer demo
                        reference: demo-transfer
                        source: balance
                        source_details: null
                        status: success
                        titan_code: null
                        transfer_code: TRF_57qtrcpodassad
                        request: 544648484
                        transferred_at: '2024-03-07T16:13:43.000Z'
                        updatedAt: '2024-03-07T16:13:43.000Z'
                        recipient:
                          active: true
                          createdAt: '2024-03-07T16:08:13.000Z'
                          currency: NGN
                          description: Demo transfers
                          domain: live
                          email: example@example.com
                          id: 12309312
                          integration: 463433
                          metadata: null
                          name: DANTE ALIGHIERI
                          recipient_code: RCP_67gq8xn0ls58535
                          type: nuban
                          updatedAt: '2024-03-07T16:37:12.000Z'
                          is_deleted: false
                          isDeleted: false
                          details:
                            authorization_code: null
                            account_number: '12334567890'
                            account_name: DANTE ALIGHIERI
                            bank_code: '999991'
                            bank_name: PalmPay
                        session:
                          provider: nip
                          id: '110001231091230120391238372113'
                        fee_charged: 0
                        fees_breakdown: null
                      - amount: 712500
                        createdAt: '2024-03-07T16:11:10.000Z'
                        currency: NGN
                        domain: live
                        failures: null
                        id: 480480480
                        integration: 463433
                        reason: food
                        reference: cf20odaindonec892384cas
                        source: balance
                        source_details: null
                        status: success
                        titan_code: null
                        transfer_code: TRF_scgho47oei0s578v
                        request: 5454545545
                        transferred_at: '2024-03-07T16:11:12.000Z'
                        updatedAt: '2024-03-07T16:11:12.000Z'
                        recipient:
                          active: true
                          createdAt: '2024-03-07T16:08:13.000Z'
                          currency: NGN
                          description: '4.0'
                          domain: live
                          email: ojoojo971@gmail.com
                          id: 73001094
                          integration: 463433
                          metadata: null
                          name: Mwana Kupona
                          recipient_code: RCP_67gq8xn0ls58535
                          type: nuban
                          updatedAt: '2024-03-07T16:37:12.000Z'
                          is_deleted: false
                          isDeleted: false
                          details:
                            authorization_code: null
                            account_number: '0000000000'
                            account_name: MWANA TAU
                            bank_code: '011'
                            bank_name: First Bank of Nigeria
                        session:
                          provider: nip
                          id: '120312192381218312812312312'
                        fee_charged: 0
                        fees_breakdown: null
                        meta:
                          total: 3
                          skipped: 0
                          perPage: 50
                          page: 1
                          pageCount: 1
                Fetch Transfer:
                  value:
                    status: true
                    message: Transfer retrieved
                    data:
                      amount: 2000
                      createdAt: 2023-04-04T10:41:58.000Z
                      currency: NGN
                      domain: live
                      failures: null
                      id: 269771800
                      integration: 463433
                      reason: Redemption amount
                      reference: abc-123-reference
                      source: balance
                      source_details: null
                      status: success
                      titan_code: null
                      transfer_code: TRF_09i424359abc123
                      request: 2484542312
                      transferred_at: 2023-04-04T10:42:01.000Z
                      updatedAt: 2023-04-04T10:42:01.000Z
                      recipient:
                        active: true
                        createdAt: 2023-04-04T10:41:12.000Z
                        currency: NGN
                        description: null
                        domain: live
                        email: customer@example.com
                        id: 51991232
                        integration: 463433
                        metadata: null
                        name: Mekatilili Menza
                        recipient_code: RCP_hcbqw7tcdojffkg
                        type: nuban
                        updatedAt: 2023-04-04T10:41:12.000Z
                        is_deleted: false
                        isDeleted: false
                        details:
                          authorization_code: null
                          account_number: 0123456789
                          account_name: MEKATILILI MENZA M
                          bank_code: 058
                          bank_name: Guaranty Trust Bank
                      session:
                        provider: nip
                        id: '00031231231231231231231230101'
                      fee_charged: 1000
                      fees_breakdown: null
                Verify Transfer:
                  value:
                    status: true
                    message: Transfer retrieved
                    data:
                      amount: 2000
                      createdAt: 2023-04-04T10:41:58.000Z
                      currency: NGN
                      domain: live
                      failures: null
                      id: 269771800
                      integration: 463433
                      reason: Redemption amount
                      reference: abc-123-reference
                      source: balance
                      source_details: null
                      status: success
                      titan_code: null
                      transfer_code: TRF_09i424359abc123
                      request: 2484542312
                      transferred_at: 2023-04-04T10:42:01.000Z
                      updatedAt: 2023-04-04T10:42:01.000Z
                      recipient:
                        active: true
                        createdAt: 2023-04-04T10:41:12.000Z
                        currency: NGN
                        description: null
                        domain: live
                        email: customer@example.com
                        id: 51991232
                        integration: 463433
                        metadata: null
                        name: Mekatilili Menza
                        recipient_code: RCP_hcbqw7tcdojffkg
                        type: nuban
                        updatedAt: 2023-04-04T10:41:12.000Z
                        is_deleted: false
                        isDeleted: false
                        details:
                          authorization_code: null
                          account_number: 0123456789
                          account_name: MEKATILILI MENZA M
                          bank_code: 058
                          bank_name: Guaranty Trust Bank
                      session:
                        provider: nip
                        id: '00031231231231231231231230101'
                      fee_charged: 1000
                      fees_breakdown: null
                Enable OTP:
                  value:
                    status: true
                    message: OTP requirement for transfers has been enabled
                Resend OTP:
                  value:
                    status: true
                    message: OTP has been resent
                Disable OTP:
                  value:
                    status: true
                    message: OTP has been sent to mobile number ending with 4321
                Finalize Disable OTP:
                  value:
                    status: true
                    message: OTP requirement for transfers has been disabled
        '401':
          description: Unauthorized operation
          content:
            application/json:
              examples:
                No-Authorization-Header:
                  value:
                    status: false
                    message: No Authorization Header was found
                Bad-Authorization-Header:
                  value:
                    status: false
                    message: 'Format is Authorization Bearer [secret key]'
                Invalid-Key:
                  value:
                    status: false
                    message: Invalid key
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
        default:
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Customer:
      allOf:
        - type: object
          required:
            - email
          properties:
            email:
              description: Customer's email address
              type: string
        - type: object
          properties:
            first_name:
              description: Customer's first name
              type: string
              example: Some
            last_name:
              description: Customer's last name
              type: string
              example: Body
            phone:
              description: Customer's phone number
              type: string
              example: '+2348123456789'
            metadata:
              description: Stringified JSON object of custom data
              type: string
        - type: object
          required:
            - authorization_code
          properties:
            authorization_code:
              description: Customer's authorization code to be deactivated
              type: string
        - type: object
          required:
            - customer
          properties:
            customer:
              description: 'Customer''s code, or email address'
              type: string
            risk_action:
              description: |
                One of the possible risk actions [ default, allow, deny ]. allow to whitelist. 
                deny to blacklist. Customers start with a default risk action.
              type: string
              enum:
                - default
                - allow
                - deny
        - type: object
          required:
            - type
            - country
            - bvn
            - bank_code
            - account_number
          properties:
            type:
              description: Predefined types of identification.
              type: string
              enum:
                - bvn
                - bank_account
            country:
              description: Two-letter country code of identification issuer
              type: string
              example: NG
            bvn:
              description: Customer's Bank Verification Number
              type: integer
              example: 0123456789
            bank_code:
              description: 'You can get the list of bank codes by calling the List Banks endpoint (https://api.paystack.co/bank).'
              type: string
              example: '007'
            account_number:
              description: Customer's bank account number.
              type: string
              example: '0111111111'
            first_name:
              description: Customer's first name
              type: string
              example: Uchenna
            last_name:
              description: Customer's last name
              type: string
              example: Okoro
    Error:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
    Response:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        data:
          type: object
  responses:
    Ok:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
              message:
                type: string
              data:
                type: object
    Created:
      description: Resource created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Entity not found
    Unauthorized:
      description: Unauthorized operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: false
            message: Invalid key
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - bearerAuth: []
